# Generated by Django 4.2.21 on 2025-05-12 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('customer_number', models.CharField(max_length=10, null=True)),
                ('doctor_name', models.CharField(max_length=100, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discount_percentage', models.FloatField(default=0)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=50, null=True)),
                ('generic_name', models.CharField(max_length=50, null=True)),
                ('hsn', models.CharField(max_length=50, null=True)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('prescription_required', models.BooleanField(null=True)),
                ('composition_id', models.IntegerField(null=True)),
                ('therapeutic_category', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.order')),
                ('payment_type', models.CharField(choices=[('UPI', 'UPI'), ('CASH', 'CASH')], max_length=4)),
                ('transaction_amount', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('password', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('shopname', models.CharField(max_length=100, null=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.register')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=10)),
                ('expiry_date', models.DateField()),
                ('average_purchase_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
            options={
                'unique_together': {('batch_number', 'product')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.batch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
            options={
                'unique_together': {('order', 'batch')},
            },
        ),
    ]
