# Generated by Django 5.2.8 on 2025-11-20 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('phone', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'api_manager',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_number', models.CharField(blank=True, max_length=10, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.FloatField(default=0)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_order',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payment', serialize=False, to='api.order')),
                ('payment_type', models.CharField(choices=[('UPI', 'UPI'), ('CASH', 'Cash'), ('CARD', 'Card')], max_length=4)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'api_payment',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('phone', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('shopname', models.CharField(max_length=100)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='api.manager')),
            ],
            options={
                'db_table': 'api_shop',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10)),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('generic_name', models.CharField(max_length=100)),
                ('hsn', models.CharField(blank=True, max_length=50, null=True)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('prescription_required', models.BooleanField(default=False)),
                ('composition_id', models.IntegerField(blank=True, null=True)),
                ('therapeutic_category', models.CharField(blank=True, max_length=100, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.shop')),
            ],
            options={
                'db_table': 'api_product',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.shop'),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('average_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='api.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='api.shop')),
            ],
            options={
                'db_table': 'api_batch',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('phone', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='api.shop')),
            ],
            options={
                'db_table': 'api_staff',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='api.batch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
            ],
            options={
                'db_table': 'api_orderitem',
                'unique_together': {('order', 'batch')},
            },
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['manager'], name='api_shop_manager_c82b74_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'product_id'], name='api_product_shop_id_c0e74d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'generic_name'], name='api_product_shop_id_d8637e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_id', 'shop')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shop', '-order_date'], name='api_order_shop_id_dc814c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shop', 'customer_number'], name='api_order_shop_id_36dd69_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['shop', 'expiry_date'], name='api_batch_shop_id_f91d20_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['shop', 'quantity_in_stock'], name='api_batch_shop_id_796236_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('batch_number', 'product', 'shop')},
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['shop', 'is_active'], name='api_staff_shop_id_ae4acc_idx'),
        ),
    ]
